### ISSUE TITLE
Updates to UML Diagrams

### ISSUE THREAD

**Issue by neetixmistry** [Alex-Anthony/SSW-322-A-Group-3-Health-Tracker-App#26]
- Any iterative changes you have made to your UML diagrams, as a result of your implementation.
- Good design means that your UML diagrams always reflect your code exactly.

**Comment by sohanchatterjee** [comment]
![SSW 322 Class Diagram M3](https://github.com/Alex-Anthony/SSW-322-A-Group-3-Health-Tracker-App/assets/74262451/942332f8-bb7c-4d05-be3c-3d9ce2034812)

**Comment by sohanchatterjee** [comment]
![SSW 322 Activity Diagram M3](https://github.com/Alex-Anthony/SSW-322-A-Group-3-Health-Tracker-App/assets/74262451/79fd5513-bcb4-4877-bb0d-6fbc62b954e2)

**Comment by sohanchatterjee** [comment]
![SSW 322 Activity Diagram M3](https://github.com/Alex-Anthony/SSW-322-A-Group-3-Health-Tracker-App/assets/74262451/f8a0e55e-ad28-4c27-a2f7-002e9f983d1d)
![SSW 322 Class Diagram M3](https://github.com/Alex-Anthony/SSW-322-A-Group-3-Health-Tracker-App/assets/74262451/afc4de23-7d57-4ebd-8c97-4034553d179e)
